logging.level.org.springframework: INFO
spring:
  security:
    oauth2:
      client:
        registration:
          uaa:
            provider: uaa
            client-id: oidc-spring-security-5
            client-secret: your-client-secret
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          uaa:
            issuer-uri: http://uaa:8090/uaa/oauth/token

